name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./student-copilot-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './student-copilot-frontend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./student-copilot-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './student-copilot-frontend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./student-copilot-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './student-copilot-frontend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./student-copilot-frontend/dist

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./student-copilot-frontend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './student-copilot-frontend/pnpm-lock.yaml'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run type-check

